default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: my_card_game_app_test

production:
  adapter: postgresql
  encoding: unicode
  #host: ec2-54-83-4-76.compute-1.amazonaws.com
  pool: 5
  #url: <%= ENV['DATABASE_URL'] %>
  url: postgres://falfiubkrtnkiy:683edb15889bcdb5c43ca5e46b069713f71488a118c9a30e670e0ccda0f3ce0a@ec2-54-225-97-112.compute-1.amazonaws.com:5432/d1mb83ha260kfn
  #host: ec2-54-225-97-112.compute-1.amazonaws.com
  #database: d1mb83ha260kfn
  #username: falfiubkrtnkiy
  #password: 683edb15889bcdb5c43ca5e46b069713f71488a118c9a30e670e0ccda0f3ce0a

staging:
  <<: *default
  database: my_card_game_app_staging
  username: my_card_game_app
  password: <%= ENV['MY_PRESET_DATABASE_PASSWORD'] %>

